language: julia
julia:
  - 0.6
os:
  - linux
notifications:
  email: true
branches:
  only:
    - master
    - docs
script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("MovingWeightedLeastSquares"); Pkg.test("MovingWeightedLeastSquares"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("MovingWeightedLeastSquares")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'cd(Pkg.dir("MovingWeightedLeastSquares")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("MovingWeightedLeastSquares")); include(joinpath("docs", "make.jl"))'
